import { MarkerType } from '@xyflow/react';
import { conceptTitleFromPlainText } from './rich-text';
import type { EditorDocument } from './types';

export const initialDocument: EditorDocument = {
  schemaVersion: 5,
  title: 'Untitled concept map',
  updatedAt: Date.now(),
  nodes: [
    {
      id: 'research',
      type: 'concept',
      position: { x: 130, y: 210 },
      draggable: true,
      deletable: true,
      data: {
        kind: 'concept',
        name: 'Research',
        label: 'Research',
        title: conceptTitleFromPlainText('Research'),
        body: { type: 'doc', content: [{ type: 'paragraph' }] },
        eyebrow: 'Starting point',
        tone: 'indigo',
        collapsed: false,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        opacity: 1,
        locked: false,
      },
    },
    {
      id: 'explore',
      type: 'concept',
      position: { x: 450, y: 115 },
      draggable: true,
      deletable: true,
      data: {
        kind: 'concept',
        name: 'Explore tools',
        label: 'Explore tools',
        title: conceptTitleFromPlainText('Explore tools'),
        body: { type: 'doc', content: [{ type: 'paragraph' }] },
        eyebrow: 'Next step',
        tone: 'ink',
        collapsed: false,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        opacity: 1,
        locked: false,
      },
    },
    {
      id: 'layers',
      type: 'concept',
      position: { x: 470, y: 340 },
      draggable: true,
      deletable: true,
      data: {
        kind: 'concept',
        name: 'Editable layers',
        label: 'Editable layers',
        title: conceptTitleFromPlainText('Editable layers'),
        body: { type: 'doc', content: [{ type: 'paragraph' }] },
        eyebrow: 'Output',
        tone: 'mint',
        collapsed: false,
        horizontalAlign: 'left',
        verticalAlign: 'top',
        opacity: 1,
        locked: false,
      },
    },
  ],
  edges: [
    {
      id: 'research-explore',
      source: 'research',
      target: 'explore',
      type: 'smoothstep',
      animated: false,
      style: { stroke: '#a9adb7', strokeWidth: 1.5 },
      markerEnd: { type: MarkerType.ArrowClosed },
      data: { label: '', kind: 'default' },
    },
    {
      id: 'research-layers',
      source: 'research',
      target: 'layers',
      type: 'smoothstep',
      animated: false,
      style: { stroke: '#a9adb7', strokeWidth: 1.5 },
      markerEnd: { type: MarkerType.ArrowClosed },
      data: { label: '', kind: 'default' },
    },
  ],
};
